#define HEART_SYMBOl "HEART"
#define SPADE_SYMBOl "SPADE"
#define DIAMOND_SYMBOl "DIAMOND"
#define CLUB_SYMBOl "CLUB"

#define CARD_MAX_VALUE 14
#define CARD_MIN_VALUE 1

#define ADD_DECK_CMD "ADD_DECK"
#define SHOW_DECK_CMD "SHOW_DECK"
#define SHOW_ALL_CMD "SHOW_ALL"
#define DEL_DECK_CMD "DEL_DECK"
#define DEL_CARD_CMD "DEL_CARD"
#define ADD_CARDS_CMD "ADD_CARDS"
#define EXIT_CMD "EXIT"
#define DECK_NUMBER_CMD "DECK_NUMBER"
#define DECK_LEN_CMD "DECK_LEN"
#define MERGE_CMD "MERGE_DECKS"
#define SHUFFLE_CMD "SHUFFLE_DECK"
#define SPLIT_CMD "SPLIT_DECK"
#define REVERSE_CMD "REVERSE_DECK"